import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
	const { data: session } = useSession();

	return (
		<>
			<Head>
				<title>Nextjs Neo4j</title>
				<meta
					name="description"
					content="Generated by Abdallah Moubarak"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main
				style={{
					width: "100%",
					height: "100vh",
					display: "flex",
					alignItems: "center",
					justifyContent: "center",
					flexFlow: "column nowrap",
					gap: "16px",
				}}
			>
				{session ? (
					<>
						<p>Signed in as {session?.user?.email}</p>
						<button
							style={{
								backgroundColor: "rgb(86 126 255 / 79%)",
								padding: "8px 24px",
								borderRadius: "55px",
								color: "whitesmoke",
							}}
							onClick={() => signOut()}
						>
							Sign out
						</button>
					</>
				) : (
					<>
						<p>Not signed in</p>
						<button
							style={{
								backgroundColor: "rgb(86 126 255 / 79%)",
								padding: "8px 24px",
								borderRadius: "55px",
								color: "whitesmoke",
							}}
							onClick={() => signIn()}
						>
							Sign in
						</button>
					</>
				)}
			</main>
		</>
	);
}
